### PR TITLE
Update path_build.php

### PR DESCRIPTION
**Pull request by WinterSilence**
Cache result +first step to `Exception::__construct(string $message, array $placeholders = [], int $code = 0, Throwable $prev)`

### CODE REVIEW

**Comment by fenric** [comment]
@WinterSilence it's benchmark code:

https://gist.github.com/fenric/cc5669137d8d53cbcf0e4890b3fad631

it's the benchmark result:

Снимок экрана 2019-11-26 в 3 56 21

your solution is very slow. **254** times slower...

**Comment by fenric** [comment]
next time, please attach tests/benchmarks to your PR.

**Comment by fenric** [comment]
and the project doesn't need message interpolation logic... it's not a framework, it's a library.

**Comment by WinterSilence** [comment]
@fenric benchmarks: slow because I add fix:
~~~
    if ($attributes) {
        $attributes = array_map('rawurlencode', $attributes);
        // decode slashes back, see Apache docs about AllowEncodedSlashes and AcceptPathInfo
        $attributes = str_replace(['%2F', '%5C'], ['/', '\\'], $attributes);
    }
~~~
+ it's cant work faster if you execute method at once. 
tests: what's additional tests you want? with not encoded attribute values?

**Comment by fenric** [comment]
@WinterSilence oh no... slow because you use strange cache logic. but, `rawurlencode` is also unnecessary.

**Comment by WinterSilence** [comment]
@WinterSilence 

> you use strange cache logic

what's strange?

> rawurlencode is also unnecessary

what reason?

**Comment by WinterSilence** [comment]
@fenric current path not normalized https://tools.ietf.org/html/rfc3986#section-6.2.2

**Pull request closed without merging**
